version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saku_tani_api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ${ENV_FILE}
    restart: always
    networks:
      - stagging-net

networks:
  stagging-net:
    external: true
