version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saku-tani-api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ${ENV_FILE}
    restart: always
    networks:
      - app-net

networks:
  stagging-net:
    name: ${DOCKER_NETWORK}
    external: true
