name: Deploy to Test

on:
  push:
    branches:
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to Test
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            PROJECT_DIR="/home/${{ secrets.VPS_USER }}/projects/saku-tani-api"

            # Cek apakah folder repo ada, kalau belum maka clone
            if [ ! -d "$PROJECT_DIR/.git" ]; then
              git clone git@github.com:username/repo-name.git "$PROJECT_DIR"
            fi

            cd "$PROJECT_DIR"
            git fetch origin
            git checkout test
            git pull origin test

            # Jalankan docker compose (gunakan `docker compose` jika pakai plugin baru)
            TAG=test ENV_FILE=.env.test PORT=${{ secrets.TEST_VPS_PORT }} docker compose up -d --build
