name: Deploy to Test

on:
  push:
    branches:
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to Test
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e

            PROJECT_DIR="/home/${{ secrets.VPS_USER }}/projects/saku-tani-api"
            REPO_URL="git@github.com:agunglaksonoputra/SakuTani-API.git"

            echo "📁 Cek direktori proyek..."
            if [ -d "$PROJECT_DIR" ]; then
              if [ ! -d "$PROJECT_DIR/.git" ]; then
                echo "⚠️ Folder sudah ada tapi bukan Git repo. Menghapusnya..."
                rm -rf "$PROJECT_DIR"
              fi
            fi

            if [ ! -d "$PROJECT_DIR" ]; then
              echo "⬇️ Clone repository..."
              git clone "$REPO_URL" "$PROJECT_DIR"
            fi

            cd "$PROJECT_DIR"

            echo "🔄 Checkout dan pull branch 'testing'..."
            git fetch origin
            git checkout testing || git checkout -b testing origin/testing
            git pull origin testing

            echo "🐳 Build dan jalankan Docker Compose..."
            TAG=test ENV_FILE=.env.test PORT=${{ secrets.TEST_VPS_PORT }} docker compose up -d --build

            echo "✅ Deploy selesai!"
