name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📁 Cek dan Persiapkan Direktori Proyek
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e
            PROJECT_DIR="${{ secrets.DIR_PROD }}"
            if [ -d "$PROJECT_DIR" ]; then
              if [ ! -d "$PROJECT_DIR/.git" ]; then
                echo "⚠️ Folder ada tapi bukan repo Git. Menghapusnya..."
                rm -rf "$PROJECT_DIR"
              fi
            fi
            if [ ! -d "$PROJECT_DIR" ]; then
              echo "⬇️ Cloning repository..."
              git clone https://github.com/agunglaksonoputra/SakuTani-API.git "$PROJECT_DIR"
            fi

            if [ ! -d "$PROJECT_DIR/.git" ]; then
              echo "❌ Gagal clone repo dengan benar!"
              exit 
            fi

      - name: 🔄 Git Checkout dan Pull Branch Main
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e
            cd "${{ secrets.DIR_PROD }}"
            git fetch origin
            git checkout main || git checkout -b main origin/main
            git pull origin main

      - name: 🧪 Buat Ulang File .env.prod
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e
            cd "${{ secrets.DIR_PROD }}"
            if [ -f ".env.prod" ]; then
              echo "🗑 Menghapus file .env.prod lama..."
              rm .env.prod
            fi
            echo "Membuat file .env.prod baru..."
            echo "${{ secrets.ENV_PROD }}" > .env.prod

      - name: 🐳 Build dan Jalankan Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e
            cd "${{ secrets.DIR_PROD }}"
            TAG=prod ENV_FILE=.env.prod PORT=3016 docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

      - name: ✅ Selesai Deploy
        run: echo "✅ Deploy production selesai!"
