name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to Production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            set -e

            PROJECT_DIR="/home/${{ secrets.VPS_USER }}/projects/production/saku-tani-api"
            REPO_URL="https://github.com/agunglaksonoputra/SakuTani-API.git"

            echo "📁 Cek direktori proyek..."
            if [ -d "$PROJECT_DIR" ]; then
              if [ ! -d "$PROJECT_DIR/.git" ]; then
                echo "⚠️ Folder sudah ada tapi bukan Git repo. Menghapusnya..."
                rm -rf "$PROJECT_DIR"
              fi
            fi

            if [ ! -d "$PROJECT_DIR" ]; then
              echo "⬇️ Clone repository..."
              git clone "$REPO_URL" "$PROJECT_DIR"
            fi

            cd "$PROJECT_DIR"

            echo "🔄 Checkout dan pull branch 'main'..."
            git fetch origin
            git checkout main || git checkout -b main origin/main
            git pull origin main

            echo "🐳 Build dan jalankan Docker Compose (Production)..."
            TAG=prod ENV_FILE=.env.prod PORT=${{ secrets.PROD_VPS_PORT }} docker compose up -d --build

            echo "✅ Deploy production selesai!"
